/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author nguye
 */
public class AccountRoleAssignmentPanel extends javax.swing.JPanel {

    private final Color bgLight = new Color(248, 249, 252); // Nền xám xanh cực nhạt
    private final Color cardWhite = Color.WHITE;
    private final Color textDark = new Color(43, 54, 116);
    private final Color textGray = new Color(163, 174, 208);
    private final Color primaryBlue = new Color(67, 97, 238);
    private final Color borderGray = new Color(230, 235, 241);

    public AccountRoleAssignmentPanel() {
        initComponents();
        setupModernLayout();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void setupModernLayout() {
        this.removeAll();
        this.setLayout(new BorderLayout(20, 20));
        this.setBackground(bgLight);
        this.setBorder(new EmptyBorder(30, 30, 30, 30));

        // === 1. HEADER ===
        JPanel header = new JPanel(new BorderLayout());
        header.setBackground(bgLight);
        
        JPanel titlePanel = new JPanel(new GridLayout(2, 1, 0, 5));
        titlePanel.setBackground(bgLight);
        JLabel title = new JLabel("Account Assign Role");
        title.setFont(new Font("Segoe UI", Font.BOLD, 26));
        title.setForeground(textDark);
        JLabel subtitle = new JLabel("Assign or update role permissions for user accounts");
        subtitle.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        subtitle.setForeground(textGray);
        titlePanel.add(title);
        titlePanel.add(subtitle);
        
        // Signed in Badge (Góc phải trên)
        JLabel signedInBadge = new JLabel("<html><span style='color:#A3AED0'>Signed in as</span> <b>System Admin</b></html>");
        signedInBadge.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        signedInBadge.setHorizontalAlignment(SwingConstants.CENTER);
        signedInBadge.setBorder(BorderFactory.createCompoundBorder(
                new RoundBorder(borderGray, 20),
                new EmptyBorder(5, 15, 5, 15)
        ));
        JPanel rightHeader = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        rightHeader.setBackground(bgLight);
        rightHeader.add(signedInBadge);

        header.add(titlePanel, BorderLayout.WEST);
        header.add(rightHeader, BorderLayout.EAST);
        this.add(header, BorderLayout.NORTH);

        // === 2. MAIN CONTENT (Chia 2 cột) ===
        JPanel content = new JPanel(new GridBagLayout());
        content.setBackground(bgLight);
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.BOTH;
        gbc.weighty = 1.0;

        // Cột Trái (List) chiếm 60%
        gbc.gridx = 0;
        gbc.weightx = 0.6;
        gbc.insets = new Insets(0, 0, 0, 10);
        content.add(createAccountListColumn(), gbc);

        // Cột Phải (Detail) chiếm 40%
        gbc.gridx = 1;
        gbc.weightx = 0.4;
        gbc.insets = new Insets(0, 10, 0, 0);
        content.add(createAssignmentColumn(), gbc);

        this.add(content, BorderLayout.CENTER);
    }
    
    // =========================================================
    // CỘT TRÁI: DANH SÁCH TÀI KHOẢN
    // =========================================================
    private JPanel createAccountListColumn() {
        RoundedPanel container = new RoundedPanel(20, cardWhite);
        container.setLayout(new BorderLayout(0, 15));
        container.setBorder(new EmptyBorder(25, 25, 25, 25));

        // Tiêu đề
        JLabel lblList = new JLabel("Account List");
        lblList.setFont(new Font("Segoe UI", Font.BOLD, 18));
        lblList.setForeground(textDark);

        // Thanh bộ lọc (Search + Combobox)
        JPanel filterPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 15, 0));
        filterPanel.setBackground(cardWhite);
        
        JTextField txtSearch = new JTextField(15);
        txtSearch.putClientProperty("JTextField.placeholderText", "Search by name or email");
        txtSearch.setPreferredSize(new Dimension(200, 35));
        
        JComboBox<String> cbDept = new JComboBox<>(new String[]{"All Departments", "IT", "Operations", "Finance", "HR"});
        cbDept.setPreferredSize(new Dimension(130, 35));
        cbDept.setBackground(Color.WHITE);
        
        JComboBox<String> cbRole = new JComboBox<>(new String[]{"All Roles", "Admin", "Manager", "User"});
        cbRole.setPreferredSize(new Dimension(100, 35));
        cbRole.setBackground(Color.WHITE);
        
        filterPanel.add(txtSearch);
        filterPanel.add(cbDept);
        filterPanel.add(cbRole);

        JPanel topSection = new JPanel(new BorderLayout(0, 15));
        topSection.setBackground(cardWhite);
        topSection.add(lblList, BorderLayout.NORTH);
        topSection.add(filterPanel, BorderLayout.CENTER);
        
        // Header của bảng (Account | Department | Current Role | Status)
        JPanel tableHeader = new JPanel(new GridLayout(1, 4, 10, 0));
        tableHeader.setBackground(new Color(248, 249, 252));
        tableHeader.setBorder(BorderFactory.createCompoundBorder(
                new RoundBorder(borderGray, 10),
                new EmptyBorder(10, 15, 10, 15)
        ));
        String[] headers = {"Account", "Department", "Current Role", "Status"};
        for (String h : headers) {
            JLabel l = new JLabel(h);
            l.setFont(new Font("Segoe UI", Font.BOLD, 12));
            l.setForeground(textGray);
            tableHeader.add(l);
        }
        topSection.add(tableHeader, BorderLayout.SOUTH);
        container.add(topSection, BorderLayout.NORTH);

        // Danh sách tài khoản (Dummy Data)
        JPanel listItems = new JPanel();
        listItems.setLayout(new BoxLayout(listItems, BoxLayout.Y_AXIS));
        listItems.setBackground(cardWhite);
        
        listItems.add(createAccountRow("John Anderson", "john.anderson@company.com", "IT", "Admin", true));
        listItems.add(createAccountRow("Emily Carter", "emily.carter@company.com", "Operations", "Manager", true));
        listItems.add(createAccountRow("David Lee", "david.lee@company.com", "Finance", "User", true));
        listItems.add(createAccountRow("Sophia Nguyen", "sophia.nguyen@company.com", "HR", "User", false));

        JScrollPane scroll = new JScrollPane(listItems);
        scroll.setBorder(null);
        scroll.getViewport().setBackground(cardWhite);
        scroll.getVerticalScrollBar().setUnitIncrement(16);
        container.add(scroll, BorderLayout.CENTER);

        return container;
    }

    private JPanel createAccountRow(String name, String email, String dept, String role, boolean isActive) {
        JPanel row = new JPanel(new GridLayout(1, 4, 10, 0));
        row.setMaximumSize(new Dimension(Integer.MAX_VALUE, 65));
        row.setBackground(cardWhite);
        row.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(0, 0, 1, 0, borderGray),
                new EmptyBorder(10, 15, 10, 15)
        ));

        // Col 1: Tên + Email
        JPanel pnlName = new JPanel(new GridLayout(2, 1));
        pnlName.setBackground(cardWhite);
        JLabel lblName = new JLabel(name);
        lblName.setFont(new Font("Segoe UI", Font.BOLD, 13));
        lblName.setForeground(textDark);
        JLabel lblEmail = new JLabel(email);
        lblEmail.setFont(new Font("Segoe UI", Font.PLAIN, 11));
        lblEmail.setForeground(textGray);
        pnlName.add(lblName);
        pnlName.add(lblEmail);
        row.add(pnlName);

        // Col 2: Department
        JLabel lblDept = new JLabel(dept);
        lblDept.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        lblDept.setForeground(textDark);
        row.add(lblDept);

        // Col 3: Role Badge
        JPanel pnlRole = new JPanel(new FlowLayout(FlowLayout.LEFT, 0, 10));
        pnlRole.setBackground(cardWhite);
        pnlRole.add(createBadge(role));
        row.add(pnlRole);

        // Col 4: Status
        String colorHex = isActive ? "#10B981" : "#A3AED0";
        String statusText = isActive ? "Active" : "Inactive";
        JLabel lblStatus = new JLabel("<html><span style='color:" + colorHex + "; font-size:14px;'>●</span> <span style='color:#2B3674;'>" + statusText + "</span></html>");
        lblStatus.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        row.add(lblStatus);

        return row;
    }

    // =========================================================
    // CỘT PHẢI: CHI TIẾT & GÁN QUYỀN
    // =========================================================
    private JPanel createAssignmentColumn() {
        RoundedPanel container = new RoundedPanel(20, cardWhite);
        container.setLayout(new BorderLayout(0, 20));
        container.setBorder(new EmptyBorder(25, 25, 25, 25));

        // Header
        JLabel lblAssign = new JLabel("Assign Role");
        lblAssign.setFont(new Font("Segoe UI", Font.BOLD, 18));
        lblAssign.setForeground(textDark);
        container.add(lblAssign, BorderLayout.NORTH);

        JPanel centerPanel = new JPanel();
        centerPanel.setLayout(new BoxLayout(centerPanel, BoxLayout.Y_AXIS));
        centerPanel.setBackground(cardWhite);

        // 1. Info User Đang chọn
        JPanel infoGrid = new JPanel(new GridLayout(4, 2, 10, 15));
        infoGrid.setBackground(cardWhite);
        infoGrid.setBorder(new EmptyBorder(0, 0, 20, 0));
        
        infoGrid.add(createLabel("Selected User", textGray));
        infoGrid.add(createLabel("Emily Carter", textDark, true));
        
        infoGrid.add(createLabel("Email", textGray));
        infoGrid.add(createLabel("emily.carter@company.com", textDark, false));
        
        infoGrid.add(createLabel("Department", textGray));
        infoGrid.add(createLabel("Operations", textDark, false));
        
        infoGrid.add(createLabel("Current Role", textGray));
        JPanel pnlCurrRole = new JPanel(new FlowLayout(FlowLayout.LEFT, 0, 0));
        pnlCurrRole.setBackground(cardWhite);
        pnlCurrRole.add(createBadge("Manager"));
        infoGrid.add(pnlCurrRole);
        
        centerPanel.add(infoGrid);

        // 2. Radio Options (Các Thẻ Card chọn quyền)
        ButtonGroup roleGroup = new ButtonGroup();
        centerPanel.add(createRoleCard("Admin", "Full access to user management, role setup, system settings, and audit logs.", roleGroup, false));
        centerPanel.add(Box.createRigidArea(new Dimension(0, 10)));
        centerPanel.add(createRoleCard("Manager", "Can manage team accounts, approve workflows, and view operational reports.", roleGroup, true));
        centerPanel.add(Box.createRigidArea(new Dimension(0, 10)));
        centerPanel.add(createRoleCard("User", "Standard access for daily operations with limited edit and approval permissions.", roleGroup, false));

        // 3. Change Summary Box
        JPanel summaryBox = new RoundedPanel(10, bgLight);
        summaryBox.setLayout(new BorderLayout());
        summaryBox.setBorder(BorderFactory.createCompoundBorder(
                new DashedBorder(textGray, 1, 5),
                new EmptyBorder(15, 15, 15, 15)
        ));
        summaryBox.setMaximumSize(new Dimension(Integer.MAX_VALUE, 80));
        JLabel lblSum = new JLabel("<html><b>Change Summary:</b><br><span style='font-size:10px; color:#666;'>Selected account will remain assigned to <b>Manager</b> role unless another role is chosen before saving.</span></html>");
        lblSum.setForeground(textDark);
        summaryBox.add(lblSum, BorderLayout.CENTER);
        
        centerPanel.add(Box.createRigidArea(new Dimension(0, 20)));
        centerPanel.add(summaryBox);
        
        container.add(centerPanel, BorderLayout.CENTER);

        // 4. Nút bấm (Cancel & Save)
        JPanel bottomBtns = new JPanel(new FlowLayout(FlowLayout.RIGHT, 10, 0));
        bottomBtns.setBackground(cardWhite);
        
        JButton btnCancel = createCustomButton("Cancel", new Color(235, 238, 244), textDark);
        JButton btnSave = createCustomButton("Save Changes", primaryBlue, Color.WHITE);
        
        bottomBtns.add(btnCancel);
        bottomBtns.add(btnSave);
        container.add(bottomBtns, BorderLayout.SOUTH);

        return container;
    }

    // =========================================================
    // CÁC HÀM TIỆN ÍCH (UTILITIES) & CUSTOM COMPONENTS
    // =========================================================
    
    private JLabel createLabel(String text, Color color) {
        return createLabel(text, color, false);
    }
    
    private JLabel createLabel(String text, Color color, boolean isBold) {
        JLabel l = new JLabel(text);
        l.setFont(new Font("Segoe UI", isBold ? Font.BOLD : Font.PLAIN, 13));
        l.setForeground(color);
        return l;
    }

    // Tạo Badge bo tròn với màu sắc tương ứng
    private JLabel createBadge(String role) {
        JLabel badge = new JLabel(" " + role + " ", SwingConstants.CENTER);
        badge.setFont(new Font("Segoe UI", Font.BOLD, 11));
        
        Color bg, fg;
        switch (role.toLowerCase()) {
            case "admin": bg = new Color(255, 235, 238); fg = new Color(220, 53, 69); break;
            case "manager": bg = new Color(255, 248, 225); fg = new Color(245, 158, 11); break;
            default: bg = new Color(237, 242, 255); fg = primaryBlue; break;
        }
        
        badge.setForeground(fg);
        badge.setOpaque(false);
        badge.setBorder(BorderFactory.createCompoundBorder(
                new RoundBorder(bg, 12, true), // border có màu nền
                new EmptyBorder(3, 10, 3, 10)
        ));
        return badge;
    }

    // Tạo thẻ Card chọn Role
    private JPanel createRoleCard(String title, String desc, ButtonGroup group, boolean isSelected) {
        JPanel card = new RoundedPanel(10, cardWhite);
        card.setLayout(new BorderLayout(10, 0));
        card.setBorder(BorderFactory.createCompoundBorder(
                new RoundBorder(isSelected ? primaryBlue : borderGray, 10),
                new EmptyBorder(12, 15, 12, 15)
        ));
        card.setMaximumSize(new Dimension(Integer.MAX_VALUE, 75));

        JRadioButton rb = new JRadioButton();
        rb.setBackground(cardWhite);
        rb.setSelected(isSelected);
        group.add(rb);
        
        JLabel lblText = new JLabel("<html><b style='color:#2B3674; font-size:12px;'>" + title + "</b><br><span style='color:#A3AED0; font-size:10px;'>" + desc + "</span></html>");
        
        card.add(rb, BorderLayout.WEST);
        card.add(lblText, BorderLayout.CENTER);
        
        // Hiệu ứng click vào card thì chọn radio
        card.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                rb.setSelected(true);
            }
        });
        
        return card;
    }

    // Nút bấm bo tròn
    private JButton createCustomButton(String text, Color bg, Color fg) {
        JButton btn = new JButton(text) {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(bg);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 10, 10);
                super.paintComponent(g);
                g2.dispose();
            }
        };
        btn.setFont(new Font("Segoe UI", Font.BOLD, 13));
        btn.setForeground(fg);
        btn.setPreferredSize(new Dimension(130, 38));
        btn.setContentAreaFilled(false);
        btn.setBorderPainted(false);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        return btn;
    }

    // --- CLASS ĐỂ VẼ PANEL CÓ BO GÓC THỰC SỰ ---
    class RoundedPanel extends JPanel {
        private int radius;
        private Color bgColor;

        public RoundedPanel(int radius, Color bgColor) {
            this.radius = radius;
            this.bgColor = bgColor;
            setOpaque(false);
        }

        @Override
        protected void paintComponent(Graphics g) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(bgColor);
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), radius, radius);
            g2.dispose();
            super.paintComponent(g);
        }
    }

    // --- CLASS ĐỂ VẼ VIỀN BO GÓC ---
    class RoundBorder implements javax.swing.border.Border {
        private Color color;
        private int radius;
        private boolean fillBg = false;

        public RoundBorder(Color color, int radius) {
            this.color = color;
            this.radius = radius;
        }
        
        public RoundBorder(Color color, int radius, boolean fillBg) {
            this.color = color;
            this.radius = radius;
            this.fillBg = fillBg;
        }

        @Override
        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(color);
            if (fillBg) {
                g2.fillRoundRect(x, y, width - 1, height - 1, radius, radius);
            } else {
                g2.setStroke(new BasicStroke(1.2f));
                g2.drawRoundRect(x, y, width - 1, height - 1, radius, radius);
            }
            g2.dispose();
        }

        @Override
        public Insets getBorderInsets(Component c) {
            return new Insets(1, 1, 1, 1);
        }

        @Override
        public boolean isBorderOpaque() { return false; }
    }
    
    // --- CLASS ĐỂ VẼ VIỀN NÉT ĐỨT (DASHED) ---
    class DashedBorder implements javax.swing.border.Border {
        private Color color;
        private int thickness;
        private int dashLength;

        public DashedBorder(Color color, int thickness, int dashLength) {
            this.color = color;
            this.thickness = thickness;
            this.dashLength = dashLength;
        }

        @Override
        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(color);
            Stroke dashed = new BasicStroke(thickness, BasicStroke.CAP_BUTT, BasicStroke.JOIN_BEVEL, 0, new float[]{dashLength}, 0);
            g2.setStroke(dashed);
            g2.drawRoundRect(x, y, width - 1, height - 1, 10, 10);
            g2.dispose();
        }

        @Override
        public Insets getBorderInsets(Component c) {
            return new Insets(thickness, thickness, thickness, thickness);
        }

        @Override
        public boolean isBorderOpaque() { return false; }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
