/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

// import cần có
import business.sql.hr_kpi.EmployeeSql;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.employee.Employee;

/**
 *
 * @author Admin
 */
public class EmployeeView extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeView
     */
    private DefaultTableModel tableModel;
    private final EmployeeSql employeeSql = new EmployeeSql();

    public EmployeeView() {
        initComponents();
        initTable();
        initEvents();
        loadDataToTable();
    }

    private void initTable() {
        tableModel = (DefaultTableModel) jTable1.getModel();
        jTable1.setModel(new DefaultTableModel(
                new Object[]{"Mã nhân viên", "Tên nhân viên", "SĐT", "Email", "Chức vụ", "Giới tính"}, 0
        ));
    }

    private void initEvents() {
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
    }

    // ====== THÊM CÁC H��M HỖ TRỢ ======
    private void loadDataToTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        ArrayList<Employee> list = employeeSql.selectAll();
        for (Employee e : list) {
            model.addRow(new Object[]{
                e.getEmployeeId(),
                e.getEmployeeName(),
                e.getPhone(),
                e.getEmail(),
                e.getRole(), // nếu model dùng getPosition() thì đổi lại
                e.getGender()
            });
        }
    }

    private Employee getEmployeeFromForm() {
        String name = txtEmployeeName.getText().trim();
        String phone = txtEmployeePhone.getText().trim();
        String email = txtEmployeeEmail.getText().trim();
        String role = txtEmployeeRole.getText().trim();
        String gender = rdoMale.isSelected() ? "Nam" : (rdoFemale.isSelected() ? "Nữ" : "");

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên nhân viên không được để trống!");
            return null;
        }
        if (phone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không được để trống!");
            return null;
        }
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email không được để trống!");
            return null;
        }
        if (role.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Role ID không được để trống! (ví dụ: R001)");
            return null;
        }
        if (gender.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn giới tính!");
            return null;
        }

        Employee e = new Employee();
        e.setEmployeeName(name);
        e.setPhone(phone);
        e.setEmail(email);
        e.setRole(role);
        e.setRoleId(role);
        e.setGender(gender);
        return e;
    }

    private String generateEmployeeId() {
        return "EMP" + System.currentTimeMillis();
    }

    private void clearForm() {
        txtEmployeeName.setText("");
        txtEmployeePhone.setText("");
        txtEmployeeEmail.setText("");
        txtEmployeeRole.setText("");
        btngGender.clearSelection();
        jTable1.clearSelection();
    }

    private String getSelectedEmployeeId() {
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            return null;
        }
        Object v = jTable1.getValueAt(row, 0);
        return v == null ? null : v.toString();
    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            return;
        }

        txtEmployeeName.setText(String.valueOf(jTable1.getValueAt(row, 1)));
        txtEmployeePhone.setText(String.valueOf(jTable1.getValueAt(row, 2)));
        txtEmployeeEmail.setText(String.valueOf(jTable1.getValueAt(row, 3)));
        txtEmployeeRole.setText(String.valueOf(jTable1.getValueAt(row, 4)));

        String gender = String.valueOf(jTable1.getValueAt(row, 5));
        rdoMale.setSelected("Nam".equalsIgnoreCase(gender));
        rdoFemale.setSelected("Nữ".equalsIgnoreCase(gender));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngGender = new javax.swing.ButtonGroup();
        pnForm = new javax.swing.JPanel();
        EmloyeeName = new javax.swing.JLabel();
        txtEmployeeName = new javax.swing.JTextField();
        EmployeePhone = new javax.swing.JLabel();
        txtEmployeePhone = new javax.swing.JTextField();
        EmployeeEmail = new javax.swing.JLabel();
        txtEmployeeEmail = new javax.swing.JTextField();
        EmployeeRole = new javax.swing.JLabel();
        txtEmployeeRole = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rdoMale = new javax.swing.JRadioButton();
        rdoFemale = new javax.swing.JRadioButton();
        tbEmployee = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnButton = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(236, 240, 241));
        setLayout(new java.awt.BorderLayout());

        pnForm.setBackground(new java.awt.Color(236, 240, 241));
        pnForm.setPreferredSize(new java.awt.Dimension(300, 0));

        EmloyeeName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmloyeeName.setText("Tên nhân viên");
        EmloyeeName.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtEmployeeName.addActionListener(this::txtEmployeeNameActionPerformed);

        EmployeePhone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmployeePhone.setText("Số điện thoại");
        EmployeePhone.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtEmployeePhone.addActionListener(this::txtEmployeePhoneActionPerformed);

        EmployeeEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmployeeEmail.setText("Email");
        EmployeeEmail.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtEmployeeEmail.addActionListener(this::txtEmployeeEmailActionPerformed);

        EmployeeRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmployeeRole.setText("Chức vụ");
        EmployeeRole.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtEmployeeRole.addActionListener(this::txtEmployeeRoleActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Giới tính");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btngGender.add(rdoMale);
        rdoMale.setText("Nam");
        rdoMale.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rdoMale.addActionListener(this::rdoMaleActionPerformed);

        btngGender.add(rdoFemale);
        rdoFemale.setText("Nữ");
        rdoFemale.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rdoFemale.addActionListener(this::rdoFemaleActionPerformed);

        javax.swing.GroupLayout pnFormLayout = new javax.swing.GroupLayout(pnForm);
        pnForm.setLayout(pnFormLayout);
        pnFormLayout.setHorizontalGroup(
            pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmloyeeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnFormLayout.createSequentialGroup()
                        .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmployeePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmployeePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmployeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmployeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmployeeRole, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnFormLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(rdoFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmployeeRole, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoMale, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnFormLayout.setVerticalGroup(
            pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(EmloyeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(EmployeePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtEmployeePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(EmployeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtEmployeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(EmployeeRole, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmployeeRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoMale, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnForm, java.awt.BorderLayout.LINE_START);

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "SĐT", "Email", "Chức vụ", "Giới tính"
            }
        ));
        tbEmployee.setViewportView(jTable1);

        add(tbEmployee, java.awt.BorderLayout.CENTER);

        pnButton.setBackground(new java.awt.Color(236, 240, 241));
        pnButton.setPreferredSize(new java.awt.Dimension(0, 40));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        pnButton.add(btnAdd);

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        pnButton.add(btnUpdate);

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        pnButton.add(btnDelete);

        btnClear.setBackground(new java.awt.Color(255, 255, 204));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setText("Làm mới");
        btnClear.addActionListener(this::btnClearActionPerformed);
        pnButton.add(btnClear);

        add(pnButton, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(236, 240, 241));
        jPanel1.setPreferredSize(new java.awt.Dimension(1051, 40));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(this::btnBackActionPerformed);

        txtSearch.addActionListener(this::txtSearchActionPerformed);

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(236, 236, 236)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Employee e = getEmployeeFromForm();
        if (e == null) {
            return;
        }

        // form không có ô mã => tự sinh
        e.setEmployeeId(generateEmployeeId());

        int rs = employeeSql.insert(e);
        if (rs > 0) {
            JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công!");
            loadDataToTable();
            clearForm();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại!");
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String id = getSelectedEmployeeId();
        if (id == null || id.isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên trong bảng để cập nhật!");
            return;
        }

        Employee e = getEmployeeFromForm();
        if (e == null) {
            return;
        }
        e.setEmployeeId(id);

        int rs = employeeSql.update(e);
        JOptionPane.showMessageDialog(this, rs > 0 ? "Cập nhật thành công!" : "Cập nhật thất bại!");
        loadDataToTable();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String id = getSelectedEmployeeId();
        if (id == null || id.isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên trong bảng để xóa!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn xóa nhân viên này?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            int rs = employeeSql.delete(id);
            JOptionPane.showMessageDialog(this, rs > 0 ? "Xóa thành công!" : "Xóa thất bại!");
            loadDataToTable();
            clearForm();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearForm();
        loadDataToTable();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String keyword = txtSearch.getText().trim();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        java.util.List<Employee> list = employeeSql.search(keyword); // cần có hàm search trong DAO
        for (Employee e : list) {
            model.addRow(new Object[]{
                e.getEmployeeId(),
                e.getEmployeeName(),
                e.getPhone(),
                e.getEmail(),
                e.getRole(), // hoặc getPosition()
                e.getGender()
            });
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeNameActionPerformed

    private void txtEmployeePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeePhoneActionPerformed

    private void txtEmployeeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeEmailActionPerformed

    private void txtEmployeeRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeRoleActionPerformed

    private void rdoMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMaleActionPerformed

    private void rdoFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoFemaleActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        java.awt.Window w = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (w instanceof DashboardView dashboard) {
            dashboard.showPanel(new HomePanel()); // hoặc panel mặc định bạn muốn
        }
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmloyeeName;
    private javax.swing.JLabel EmployeeEmail;
    private javax.swing.JLabel EmployeePhone;
    private javax.swing.JLabel EmployeeRole;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup btngGender;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnButton;
    private javax.swing.JPanel pnForm;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JScrollPane tbEmployee;
    private javax.swing.JTextField txtEmployeeEmail;
    private javax.swing.JTextField txtEmployeeName;
    private javax.swing.JTextField txtEmployeePhone;
    private javax.swing.JTextField txtEmployeeRole;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
