/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Admin
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Icon = new javax.swing.JLabel();
        SystemName = new javax.swing.JLabel();
        Separator = new javax.swing.JSeparator();
        Greeting = new javax.swing.JLabel();
        ClassName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 240, 241));
        setLayout(new java.awt.GridBagLayout());

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/market-Photoroom.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 212, 0, 0);
        add(Icon, gridBagConstraints);

        SystemName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SystemName.setForeground(new java.awt.Color(0, 22, 151));
        SystemName.setText("HỆ THỐNG QUẢN LÝ SIÊU THỊ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 83, 0, 86);
        add(SystemName, gridBagConstraints);

        Separator.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 283;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 110, 0, 0);
        add(Separator, gridBagConstraints);

        Greeting.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Greeting.setForeground(new java.awt.Color(51, 51, 51));
        Greeting.setText("Chào mừng bạn đến với hệ thống!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 143, 0, 0);
        add(Greeting, gridBagConstraints);

        ClassName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        ClassName.setForeground(new java.awt.Color(51, 51, 51));
        ClassName.setText("Nhóm - IS216.Q22");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 193, 64, 0);
        add(ClassName, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClassName;
    private javax.swing.JLabel Greeting;
    private javax.swing.JLabel Icon;
    private javax.swing.JSeparator Separator;
    private javax.swing.JLabel SystemName;
    // End of variables declaration//GEN-END:variables
}
