/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import business.sql.sales_order.OrdersSql;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.order.Order;

/**
 *
 * @author Admin
 */
public class OrderView extends javax.swing.JPanel {

    /**
     * Creates new form OrderView
     */
    public OrderView() {
        initComponents();
        
        // Khởi tạo bổ sung theo style thống nhất
        initTableModel();
        loadDataToTable();
        
        this.revalidate();
        this.repaint();
    }

    // ==========================================
    // Khởi tạo model bảng đúng cột theo DB
    // ==========================================
    private void initTableModel() {
        DefaultTableModel model = new DefaultTableModel(
            new Object [] { "Mã đơn", "Khách hàng", "Ngày", "Tổng tiền", "Trạng thái" }, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Không cho sửa trực tiếp trên bảng
            }
        };
        jTable1.setModel(model);
    }

    // ==========================================
    // Load toàn bộ dữ liệu đơn hàng từ DB lên bảng
    // ==========================================
    private void loadDataToTable() {
        try {
            // Sử dụng singleton OrdersSql đã viết
            List<Order> list = OrdersSql.getInstance().selectAll();
            fillTable(list);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi tải danh sách đơn hàng: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void fillTable(List<Order> list) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (Order o : list) {
            model.addRow(new Object[]{
                o.getOrderId(),
                o.getCustomerId(),
                o.getOrderDate(),
                o.getTotalAmount(),
                o.getStatus()
            });
        }
    }

    // ==========================================
    // Hàm điều hướng Panel (Thống nhất với Dashboard)
    // ==========================================
    private void showPanel(javax.swing.JPanel panel) {
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof javax.swing.JFrame frame) {
            frame.setContentPane(panel);
            frame.revalidate();
            frame.repaint();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnTop = new javax.swing.JPanel();
        Status = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        tbOrder = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnButton = new javax.swing.JPanel();
        btnDetail = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnIssueAnInvoice = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnTop.setBackground(new java.awt.Color(236, 240, 241));
        pnTop.setPreferredSize(new java.awt.Dimension(342, 32));
        pnTop.setLayout(new java.awt.GridBagLayout());

        Status.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Status.setText("Trạng thái");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 184, 0, 0);
        pnTop.add(Status, gridBagConstraints);

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Đang xử lý", "Đã giao", "Đã hủy", " " }));
        cbStatus.addActionListener(this::cbStatusActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 5, 172);
        pnTop.add(cbStatus, gridBagConstraints);

        add(pnTop, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã đơn", "Khách hàng", "Ngày", "Tổng tiền", "Trạng thái"
            }
        ));
        tbOrder.setViewportView(jTable1);

        add(tbOrder, java.awt.BorderLayout.CENTER);

        pnButton.setBackground(new java.awt.Color(236, 240, 241));
        pnButton.setPreferredSize(new java.awt.Dimension(358, 40));
        pnButton.setLayout(new java.awt.GridBagLayout());

        btnDetail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDetail.setText("Xem chi tiết");
        btnDetail.addActionListener(this::btnDetailActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 44, 12, 0);
        pnButton.add(btnDetail, gridBagConstraints);

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setText("Cập nhật trạng thái");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 12, 0);
        pnButton.add(btnUpdate, gridBagConstraints);

        btnIssueAnInvoice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIssueAnInvoice.setForeground(new java.awt.Color(204, 0, 0));
        btnIssueAnInvoice.setText("Xuất hóa đơn");
        btnIssueAnInvoice.addActionListener(this::btnIssueAnInvoiceActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 12, 59);
        pnButton.add(btnIssueAnInvoice, gridBagConstraints);

        add(pnButton, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một đơn hàng để cập nhật!");
            return;
        }
        
        String orderId = jTable1.getValueAt(row, 0).toString();
        String currentStatus = jTable1.getValueAt(row, 4).toString();
        
        // Tạo mảng lựa chọn khớp với DB
        String[] statuses = {"Processing", "Completed", "Cancelled"};
        String newStatus = (String) JOptionPane.showInputDialog(this, 
                "Chọn trạng thái mới cho đơn hàng " + orderId,
                "Cập nhật trạng thái", JOptionPane.QUESTION_MESSAGE, null, 
                statuses, currentStatus);
        
        if (newStatus != null && !newStatus.equals(currentStatus)) {
            try {
                // Giả định OrdersSql đã có hàm updateStatus hoặc dùng update chung
                Order o = OrdersSql.getInstance().selectById(orderId);
                o.setStatus(newStatus);
                int result = OrdersSql.getInstance().update(o);
                
                if (result > 0) {
                    JOptionPane.showMessageDialog(this, "Cập nhật trạng thái thành công!");
                    loadDataToTable();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        String selected = cbStatus.getSelectedItem().toString();
        if (selected.equals("Tất cả")) {
            loadDataToTable();
        } else {
            // Tận dụng hàm search hoặc selectByCondition
            try {
                List<Order> list = OrdersSql.getInstance().selectAll(); // Hoặc viết hàm lọc riêng
                List<Order> filtered = list.stream()
                        .filter(o -> o.getStatus().equalsIgnoreCase(selected))
                        .toList();
                fillTable(filtered);
            } catch (Exception ex) { ex.printStackTrace(); }
        }
    }//GEN-LAST:event_cbStatusActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn đơn hàng muốn xem chi tiết!");
            return;
        }
        String orderId = jTable1.getValueAt(row, 0).toString();
        
        // TODO: Chuyển sang OrderDetailView và truyền orderId vào
        JOptionPane.showMessageDialog(this, "Chức năng xem chi tiết đơn hàng: " + orderId);
        // showPanel(new OrderDetailView(orderId));
    }//GEN-LAST:event_btnDetailActionPerformed

    private void btnIssueAnInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueAnInvoiceActionPerformed
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn đơn hàng để xuất hóa đơn!");
            return;
        }
        
        // Sử dụng PDFExporter hoặc ExcelExporter trong common.report
        JOptionPane.showMessageDialog(this, "Đang khởi tạo trình xuất hóa đơn (PDF/Excel)...");
        // new PDFExporter().exportOrder(jTable1.getValueAt(row, 0).toString());
    }//GEN-LAST:event_btnIssueAnInvoiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Status;
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnIssueAnInvoice;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnButton;
    private javax.swing.JPanel pnTop;
    private javax.swing.JScrollPane tbOrder;
    // End of variables declaration//GEN-END:variables
}
