/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Admin
 */
import business.sql.prod_inventory.ProductsSql;
import common.utils.Validator;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.product.Product;

public class ProductView extends javax.swing.JPanel {

    /**
     * Creates new form ProductView
     */
    public ProductView() {
        initComponents();
        initTableModel();
        initEvents();
        loadDataToTable();

        this.revalidate();
        this.repaint();
    }

    private void initTableModel() {
        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"Mã sản phẩm", "Tên sản phẩm", "Giá", "Số lượng", "Loại sản phẩm"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblProducts.setModel(model);
    }

    private void initEvents() {
        tblProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductView.this.tblProductsMouseClicked(evt); // gọi hàm của class ngoài
            }
        });
    }

    private void fillTable(List<Product> list) {
        DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();
        model.setRowCount(0);
        for (Product p : list) {
            model.addRow(new Object[]{
                p.getProductId(),
                p.getProductName(),
                p.getBasePrice(),
                p.getQuantity(),
                p.getCategoryId()
            });
        }
    }

    private boolean validateInput() {
        if (Validator.isEmpty(txtName.getText())) {
            JOptionPane.showMessageDialog(this, "Tên sản phẩm không được rỗng!");
            return false;
        }
        if (!Validator.isPositiveInteger(txtQuantity.getText())) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là số nguyên dương!");
            return false;
        }
        try {
            BigDecimal bigDecimal = new BigDecimal(txtPrice.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Giá không hợp lệ!");
            return false;
        }
        return true;
    }

    private Product getProductFromForm() {
        Product p = new Product();

        String name = txtName.getText().trim();
        String priceText = txtPrice.getText().trim();
        String qtyText = txtQuantity.getText().trim();
        String categoryId = txtCategory.getText().trim();

        if (name.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Tên sản phẩm không được rỗng!");
            return null;
        }
        if (priceText.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Giá không được rỗng!");
            return null;
        }
        if (qtyText.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Số lượng không được rỗng!");
            return null;
        }
        if (categoryId.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Loại sản phẩm (category_id) không được rỗng!");
            return null;
        }

        try {
            java.math.BigDecimal price = new java.math.BigDecimal(priceText);
            int qty = Integer.parseInt(qtyText);

            // product_id: tự sinh tạm thời
            String productId = "PROD_" + System.currentTimeMillis();

            p.setProductId(productId);
            p.setProductName(name);
            p.setBasePrice(price);
            p.setQuantity(qty);
            p.setCategoryId(categoryId);

            // tạm hard-code để qua FK (phải tồn tại trong DB)
            p.setSupplierId("SUP001");
            p.setStoreId("ST001");
            p.setUnit("Cái");

            return p;
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Giá/Số lượng không hợp lệ!");
            return null;
        }
    }

    private void showPanel(javax.swing.JPanel panel) {
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof javax.swing.JFrame frame) {
            frame.setContentPane(panel);
            frame.revalidate();
            frame.repaint();
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnForm = new javax.swing.JPanel();
        ProductName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        price = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        Quantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        Category = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        pnlButton = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnExportPDF = new javax.swing.JButton();

        setBackground(new java.awt.Color(236, 240, 241));
        setLayout(new java.awt.BorderLayout());

        pnForm.setBackground(new java.awt.Color(236, 240, 241));
        pnForm.setPreferredSize(new java.awt.Dimension(280, 0));
        pnForm.setLayout(new java.awt.GridBagLayout());

        ProductName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ProductName.setText("Tên sản phẩm");
        ProductName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 182;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 0, 0);
        pnForm.add(ProductName, gridBagConstraints);

        txtName.addActionListener(this::txtNameActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 210;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        pnForm.add(txtName, gridBagConstraints);

        price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        price.setText("Giá");
        price.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 252;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        pnForm.add(price, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 210;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        pnForm.add(txtPrice, gridBagConstraints);

        Quantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Quantity.setText("Số lượng");
        Quantity.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 214;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        pnForm.add(Quantity, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 210;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        pnForm.add(txtQuantity, gridBagConstraints);

        Category.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Category.setText("Loại sản phẩm");
        Category.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 179;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        pnForm.add(Category, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 210;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 2, 0);
        pnForm.add(txtCategory, gridBagConstraints);

        add(pnForm, java.awt.BorderLayout.LINE_START);

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        tblProducts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Giá", "Số lượng", "Loại sản phẩm"
            }
        ));
        jScrollPane1.setViewportView(tblProducts);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlButton.setBackground(new java.awt.Color(236, 240, 241));
        pnlButton.setPreferredSize(new java.awt.Dimension(0, 60));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        pnlButton.add(btnAdd);

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        pnlButton.add(btnUpdate);

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        pnlButton.add(btnDelete);

        btnClear.setBackground(new java.awt.Color(255, 255, 204));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setText("Làm mới");
        btnClear.addActionListener(this::btnClearActionPerformed);
        pnlButton.add(btnClear);

        add(pnlButton, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(236, 240, 241));
        jPanel1.setPreferredSize(new java.awt.Dimension(877, 35));

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        btnExportPDF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExportPDF.setText("Xuất Execl");
        btnExportPDF.addActionListener(this::btnExportPDFActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExportPDF)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnExportPDF))
                .addGap(3, 3, 3))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (!validateInput()) {
            return;
        }

        Product p = getProductFromForm();
        if (p == null) {
            return;
        }

        // Nếu chưa có productId thì tự sinh
        if (p.getProductId() == null || p.getProductId().trim().isEmpty()) {
            p.setProductId("PROD" + (System.currentTimeMillis() % 1000000));
        }

        // Bắt buộc cho FK (đảm bảo các mã này tồn tại trong DB)
        if (p.getCategoryId() == null || p.getCategoryId().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Loại sản phẩm (category_id) không được rỗng!");
            return;
        }

        if (p.getSupplierId() == null || p.getSupplierId().trim().isEmpty()) {
            p.setSupplierId("SUP001"); // tạm mặc định
        }

        if (p.getStoreId() == null || p.getStoreId().trim().isEmpty()) {
            p.setStoreId("ST001"); // tạm mặc định
        }

        if (p.getUnit() == null || p.getUnit().trim().isEmpty()) {
            p.setUnit("Cái");
        }

        boolean ok = ProductsSql.getInstance().insert(p);

        if (ok) {
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            loadDataToTable();
            btnClearActionPerformed(null);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Thêm thất bại! Kiểm tra category_id / supplier_id / store_id có tồn tại trong DB.",
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = tblProducts.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Chọn sản phẩm để cập nhật!");
            return;
        }

        if (!validateInput()) {
            return;
        }

        Product p = getProductFromForm();
        if (p == null) {
            return;
        }

        // Giữ nguyên ID của dòng đang chọn
        String id = tblProducts.getValueAt(row, 0).toString();
        p.setProductId(id);

        // Nếu UI chưa có ô supplier/store thì set mặc định để không lỗi FK
        if (p.getSupplierId() == null || p.getSupplierId().trim().isEmpty()) {
            p.setSupplierId("SUP001");
        }
        if (p.getStoreId() == null || p.getStoreId().trim().isEmpty()) {
            p.setStoreId("ST001");
        }
        if (p.getUnit() == null || p.getUnit().trim().isEmpty()) {
            p.setUnit("Cái");
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Cập nhật sản phẩm " + id + "?",
                "Xác nhận cập nhật",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            boolean ok = ProductsSql.getInstance().update(p);
            if (ok) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                loadDataToTable();
                btnClearActionPerformed(null);
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = tblProducts.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Chọn sản phẩm để xóa!");
            return;
        }
        String id = tblProducts.getValueAt(row, 0).toString();
        if (JOptionPane.showConfirmDialog(this, "Xóa sản phẩm " + id + "?") == JOptionPane.YES_OPTION) {
            if (ProductsSql.getInstance().delete(id)) {
                loadDataToTable();
                btnClearActionPerformed(null);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtName.setText("");
        txtPrice.setText("");
        txtQuantity.setText("");
        txtCategory.setText("");
        tblProducts.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String keyword = txtSearch.getText().trim();
        List<Product> list = ProductsSql.getInstance().searchByName(keyword);
        fillTable(list);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnExportPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportPDFActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Lấy dữ liệu từ bảng
            List<Map<String, Object>> productList = getAllProductsFromTable();

            if (productList.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Không có dữ liệu để xuất!",
                        "Thông báo",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            // 2. Chọn nơi lưu file
            javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
            fileChooser.setDialogTitle("Lưu file Excel");
            fileChooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
            fileChooser.setSelectedFile(new java.io.File("SanPham_" + System.currentTimeMillis() + ".xlsx"));

            int userSelection = fileChooser.showSaveDialog(this);
            if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
                String filePath = fileChooser.getSelectedFile().getAbsolutePath();

                // 3. Gọi service xuất Excel
                common.report.ExcelExporter.exportInventoryFromMap(productList, filePath);

                // 4. Hiển thị thành công
                javax.swing.JOptionPane.showMessageDialog(this,
                        "✅ Xuất Excel thành công!\nFile: " + filePath,
                        "Thành công",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "❌ Lỗi xuất Excel: " + ex.getMessage(),
                    "Lỗi",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnExportPDFActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void tblProductsMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblProducts.getSelectedRow();
        if (row < 0) {
            return;
        }

        Object nameObj = tblProducts.getValueAt(row, 1);
        Object priceObj = tblProducts.getValueAt(row, 2);
        Object qtyObj = tblProducts.getValueAt(row, 3);
        Object categoryObj = tblProducts.getValueAt(row, 4);

        txtName.setText(nameObj == null ? "" : nameObj.toString());
        txtPrice.setText(priceObj == null ? "" : priceObj.toString());
        txtQuantity.setText(qtyObj == null ? "" : qtyObj.toString());
        txtCategory.setText(categoryObj == null ? "" : categoryObj.toString());
    }
// Helper: lấy tất cả dữ liệu từ JTable

    private List<Map<String, Object>> getAllProductsFromTable() {
        List<Map<String, Object>> list = new ArrayList<>();
        int rowCount = tblProducts.getRowCount();

        for (int i = 0; i < rowCount; i++) {
            Map<String, Object> row = new HashMap<>();
            row.put("productId", tblProducts.getValueAt(i, 0));
            row.put("productName", tblProducts.getValueAt(i, 1));
            row.put("price", tblProducts.getValueAt(i, 2));
            row.put("quantity", tblProducts.getValueAt(i, 3));
            list.add(row);
        }
        return list;
    }

    public void loadDataToTable() {
        DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();
        model.setRowCount(0);

        try {
            List<model.product.Product> list
                    = business.sql.prod_inventory.ProductsSql.getInstance().selectAll();

            for (model.product.Product p : list) {
                Object[] row = {
                    p.getProductId(),
                    p.getProductName(),
                    p.getBasePrice(),
                    p.getQuantity(),
                    p.getCategoryId() // thêm cột Loại SP
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            System.out.println("Lỗi load bảng: " + e.getMessage());
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Category;
    private javax.swing.JLabel ProductName;
    private javax.swing.JLabel Quantity;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExportPDF;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnForm;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JLabel price;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
