/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author nguye
 */
public class RoleManagementPanel extends javax.swing.JPanel {

    private final Color bgLight = new Color(248, 249, 252); 
    private final Color cardWhite = Color.WHITE;
    private final Color textDark = new Color(43, 54, 116);
    private final Color textGray = new Color(163, 174, 208);
    private final Color primaryBlue = new Color(67, 97, 238);
    private final Color borderGray = new Color(230, 235, 241);

    public RoleManagementPanel() {
        initComponents();
        setupModernLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void setupModernLayout() {
        this.removeAll();
        this.setLayout(new BorderLayout(20, 20));
        this.setBackground(bgLight);
        this.setBorder(new EmptyBorder(30, 30, 30, 30));

        // === 1. HEADER ===
        JPanel header = new JPanel(new BorderLayout());
        header.setBackground(bgLight);
        
        JPanel titlePanel = new JPanel(new GridLayout(2, 1, 0, 5));
        titlePanel.setBackground(bgLight);
        JLabel title = new JLabel("Roles & Permissions");
        title.setFont(new Font("Segoe UI", Font.BOLD, 26));
        title.setForeground(textDark);
        JLabel subtitle = new JLabel("Create new roles and manage system module permissions");
        subtitle.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        subtitle.setForeground(textGray);
        titlePanel.add(title);
        titlePanel.add(subtitle);
        header.add(titlePanel, BorderLayout.WEST);
        this.add(header, BorderLayout.NORTH);

        // === 2. MAIN CONTENT ===
        JPanel content = new JPanel(new BorderLayout(0, 25));
        content.setBackground(bgLight);
        
        // Top: Form thêm Role mới
        content.add(createFormCard(), BorderLayout.NORTH);
        
        // Bottom: Bảng danh sách các Role hiện có
        content.add(createRoleListCard(), BorderLayout.CENTER);

        this.add(content, BorderLayout.CENTER);
    }

    // =========================================================
    // CARD: FORM THÊM ROLE MỚI (Đúng yêu cầu của Tùng)
    // =========================================================
    private JPanel createFormCard() {
        RoundedPanel card = new RoundedPanel(20, cardWhite);
        card.setLayout(new BorderLayout(0, 20));
        card.setBorder(new EmptyBorder(25, 25, 25, 25));

        // Tiêu đề Card
        JLabel lblCardTitle = new JLabel("Create New Role");
        lblCardTitle.setFont(new Font("Segoe UI", Font.BOLD, 18));
        lblCardTitle.setForeground(textDark);
        card.add(lblCardTitle, BorderLayout.NORTH);

        JPanel formBody = new JPanel(new BorderLayout(0, 15));
        formBody.setBackground(cardWhite);

        // 1. Dòng Function (Combobox)
        JPanel funcPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 0, 0));
        funcPanel.setBackground(cardWhite);
        JLabel lblFunc = new JLabel("Target Function:  ");
        lblFunc.setFont(new Font("Segoe UI", Font.BOLD, 13));
        lblFunc.setForeground(textDark);
        
        JComboBox<String> cbFunction = new JComboBox<>(new String[]{
            "F_SYS - Quản lý hệ thống", 
            "F_STORE - Quản lý cửa hàng", 
            "F_EMP - Quản lý nhân viên",
            "F_PROD - Quản lý sản phẩm"
        });
        cbFunction.setPreferredSize(new Dimension(300, 35));
        cbFunction.setBackground(Color.WHITE);
        cbFunction.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        
        funcPanel.add(lblFunc);
        funcPanel.add(cbFunction);
        formBody.add(funcPanel, BorderLayout.NORTH);

        // 2. Bảng nhập liệu: Role Name + Các Checkbox Quyền
        JPanel tablePanel = new JPanel(new GridBagLayout());
        tablePanel.setBackground(new Color(248, 249, 252));
        tablePanel.setBorder(BorderFactory.createCompoundBorder(
                new RoundBorder(borderGray, 12),
                new EmptyBorder(15, 15, 15, 15)
        ));
        
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 10, 10, 10);

        // Dòng 1: Tiêu đề các cột
        String[] headers = {"Role Name", "View", "Add", "Edit", "Delete", "Export"};
        double[] weights = {0.5, 0.1, 0.1, 0.1, 0.1, 0.1}; // Role name chiếm 50% chiều rộng
        
        gbc.gridy = 0;
        for (int i = 0; i < headers.length; i++) {
            gbc.gridx = i;
            gbc.weightx = weights[i];
            JLabel lbl = new JLabel(headers[i]);
            lbl.setFont(new Font("Segoe UI", Font.BOLD, 13));
            lbl.setForeground(textGray);
            if (i > 0) lbl.setHorizontalAlignment(SwingConstants.CENTER); // Căn giữa cho chữ của Checkbox
            tablePanel.add(lbl, gbc);
        }

        // Dòng 2: Ô nhập liệu (TextField & Checkbox)
        gbc.gridy = 1;
        gbc.insets = new Insets(0, 10, 0, 10);
        
        // Ô nhập Role Name
        gbc.gridx = 0;
        JTextField txtRoleName = new JTextField();
        txtRoleName.setPreferredSize(new Dimension(200, 38));
        txtRoleName.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        txtRoleName.setBorder(BorderFactory.createCompoundBorder(
                new RoundBorder(borderGray, 8),
                new EmptyBorder(0, 10, 0, 10)
        ));
        txtRoleName.putClientProperty("JTextField.placeholderText", "Ví dụ: R_MANAGER_SALE");
        tablePanel.add(txtRoleName, gbc);
        
        // Các ô Checkbox
        for (int i = 1; i <= 5; i++) {
            gbc.gridx = i;
            JCheckBox cb = new JCheckBox();
            cb.setBackground(new Color(248, 249, 252));
            cb.setHorizontalAlignment(SwingConstants.CENTER);
            cb.setCursor(new Cursor(Cursor.HAND_CURSOR));
            tablePanel.add(cb, gbc);
        }

        formBody.add(tablePanel, BorderLayout.CENTER);

        // 3. Nút Thêm (Add Button)
        JPanel btnPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT, 0, 0));
        btnPanel.setBackground(cardWhite);
        JButton btnAdd = createCustomButton("+ Thêm mới", primaryBlue, Color.WHITE);
        btnPanel.add(btnAdd);
        formBody.add(btnPanel, BorderLayout.SOUTH);

        card.add(formBody, BorderLayout.CENTER);
        return card;
    }

    // =========================================================
    // CARD: DANH SÁCH ROLE HIỆN CÓ (Bonus cho giao diện đẹp)
    // =========================================================
    private JPanel createRoleListCard() {
        RoundedPanel card = new RoundedPanel(20, cardWhite);
        card.setLayout(new BorderLayout(0, 15));
        card.setBorder(new EmptyBorder(25, 25, 25, 25));

        JLabel lblList = new JLabel("Existing Roles");
        lblList.setFont(new Font("Segoe UI", Font.BOLD, 18));
        lblList.setForeground(textDark);
        card.add(lblList, BorderLayout.NORTH);

        // Khung chứa danh sách
        JPanel listItems = new JPanel();
        listItems.setLayout(new BoxLayout(listItems, BoxLayout.Y_AXIS));
        listItems.setBackground(cardWhite);
        
        // Header của danh sách
        JPanel headerRow = new JPanel(new GridLayout(1, 4, 10, 0));
        headerRow.setBackground(cardWhite);
        headerRow.setBorder(new EmptyBorder(0, 10, 10, 10));
        String[] cols = {"Role Code", "Function", "Permissions", "Status"};
        for (String c : cols) {
            JLabel l = new JLabel(c);
            l.setFont(new Font("Segoe UI", Font.BOLD, 12));
            l.setForeground(textGray);
            headerRow.add(l);
        }
        
        JPanel listWrapper = new JPanel(new BorderLayout());
        listWrapper.setBackground(cardWhite);
        listWrapper.add(headerRow, BorderLayout.NORTH);
        
        // Thêm dữ liệu mẫu
        listItems.add(createRoleRow("R_ADMIN_ALL", "F_SYS", "View, Add, Edit, Delete, Export"));
        listItems.add(createRoleRow("R_STORE_MNG", "F_STORE", "View, Add, Edit, Delete, Export"));
        listItems.add(createRoleRow("R_STAFF_SALE", "F_ORDER", "View, Add, Export"));
        listItems.add(createRoleRow("R_STAFF_VIEW_PROD", "F_PROD", "View"));

        JScrollPane scroll = new JScrollPane(listItems);
        scroll.setBorder(BorderFactory.createMatteBorder(1, 0, 0, 0, borderGray));
        scroll.getViewport().setBackground(cardWhite);
        listWrapper.add(scroll, BorderLayout.CENTER);

        card.add(listWrapper, BorderLayout.CENTER);
        return card;
    }

    private JPanel createRoleRow(String roleCode, String function, String perms) {
        JPanel row = new JPanel(new GridLayout(1, 4, 10, 0));
        row.setMaximumSize(new Dimension(Integer.MAX_VALUE, 50));
        row.setBackground(cardWhite);
        row.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(0, 0, 1, 0, borderGray),
                new EmptyBorder(10, 10, 10, 10)
        ));

        JLabel lblCode = new JLabel(roleCode);
        lblCode.setFont(new Font("Segoe UI", Font.BOLD, 13));
        lblCode.setForeground(textDark);
        row.add(lblCode);

        JLabel lblFunc = new JLabel(function);
        lblFunc.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        lblFunc.setForeground(textGray);
        row.add(lblFunc);

        JLabel lblPerms = new JLabel("<html><span style='color:#4361EE; font-size:11px;'>" + perms + "</span></html>");
        row.add(lblPerms);

        JLabel lblStatus = new JLabel("<html><span style='color:#10B981; font-size:14px;'>●</span> <span style='color:#2B3674;'>Active</span></html>");
        lblStatus.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        row.add(lblStatus);

        return row;
    }

    // =========================================================
    // UI COMPONENTS TIỆN ÍCH
    // =========================================================
    
    private JButton createCustomButton(String text, Color bg, Color fg) {
        JButton btn = new JButton(text) {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(bg);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 10, 10);
                super.paintComponent(g);
                g2.dispose();
            }
        };
        btn.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btn.setForeground(fg);
        btn.setPreferredSize(new Dimension(140, 42));
        btn.setContentAreaFilled(false);
        btn.setBorderPainted(false);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        return btn;
    }

    class RoundedPanel extends JPanel {
        private int radius;
        private Color bgColor;

        public RoundedPanel(int radius, Color bgColor) {
            this.radius = radius;
            this.bgColor = bgColor;
            setOpaque(false);
        }

        @Override
        protected void paintComponent(Graphics g) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(bgColor);
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), radius, radius);
            g2.dispose();
            super.paintComponent(g);
        }
    }

    class RoundBorder implements javax.swing.border.Border {
        private Color color;
        private int radius;

        public RoundBorder(Color color, int radius) {
            this.color = color;
            this.radius = radius;
        }

        @Override
        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(color);
            g2.setStroke(new BasicStroke(1.2f));
            g2.drawRoundRect(x, y, width - 1, height - 1, radius, radius);
            g2.dispose();
        }

        @Override
        public Insets getBorderInsets(Component c) {
            return new Insets(1, 1, 1, 1);
        }

        @Override
        public boolean isBorderOpaque() { return false; }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
