/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;

/**
 *
 * @author nguye
 */
public class RoleManagementPanel extends javax.swing.JPanel {

    private final Color bgLight = new Color(248, 249, 252); 
    private final Color cardWhite = Color.WHITE;
    private final Color textDark = new Color(43, 54, 116);
    private final Color textGray = new Color(163, 174, 208);
    private final Color primaryBlue = new Color(67, 97, 238);
    private final Color borderGray = new Color(230, 235, 241);

    public RoleManagementPanel() {
        initComponents();
        setupModernLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void setupModernLayout() {
        this.removeAll();
        this.setLayout(new BorderLayout(0, 20));
        this.setBackground(bgLight);
        this.setBorder(new EmptyBorder(30, 30, 30, 30));

        // === 1. HEADER & NÚT THÊM MỚI ===
        JPanel header = new JPanel(new BorderLayout());
        header.setBackground(bgLight);
        
        JPanel titlePanel = new JPanel(new GridLayout(2, 1, 0, 5));
        titlePanel.setBackground(bgLight);
        JLabel title = new JLabel("Ma Trận Phân Quyền");
        title.setFont(new Font("Segoe UI", Font.BOLD, 26));
        title.setForeground(textDark);
        JLabel subtitle = new JLabel("Quản lý tập trung quyền hạn của tất cả các vai trò trong hệ thống");
        subtitle.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        subtitle.setForeground(textGray);
        titlePanel.add(title);
        titlePanel.add(subtitle);
        
        JButton btnAddNew = createCustomButton("+ Thêm vai trò mới", primaryBlue, Color.WHITE);
        
        header.add(titlePanel, BorderLayout.WEST);
        header.add(btnAddNew, BorderLayout.EAST);
        this.add(header, BorderLayout.NORTH);

        // === 2. MAIN CONTENT (MA TRẬN TỔNG THỂ) ===
        JPanel content = new JPanel(new BorderLayout());
        content.setBackground(bgLight);
        
        content.add(createMatrixPanel(), BorderLayout.CENTER);

        this.add(content, BorderLayout.CENTER);
    }

    // =========================================================
    // PHẦN BẢNG MA TRẬN (LÀM THEO BẢN VẼ CỦA TÙNG)
    // =========================================================
    private JPanel createMatrixPanel() {
        RoundedPanel container = new RoundedPanel(20, cardWhite);
        container.setLayout(new BorderLayout(0, 20));
        container.setBorder(new EmptyBorder(30, 30, 30, 30));

        // Dữ liệu
        String[] roles = {"Quản trị viên", "Quản lý cửa hàng", "Nhân viên bán hàng", "Nhân viên kho"};
        // ĐÃ THÊM MỤC MỚI VÀO CUỐI MẢNG
        String[] actions = {"Xem", "Thêm", "Sửa", "Xóa", "Xuất file", "+ Thêm quyền hạn"};

        JPanel tablePanel = new JPanel(new GridBagLayout());
        tablePanel.setBackground(cardWhite);
        GridBagConstraints gbc = new GridBagConstraints();
        
        gbc.fill = GridBagConstraints.BOTH;

        // --- DÒNG HEADER ---
        gbc.gridy = 0;
        gbc.weighty = 0.0; // Header thì giữ nguyên kích thước gốc
        gbc.insets = new Insets(0, 0, 20, 0);
        
        gbc.gridx = 0;
        gbc.weightx = 0.2;
        JLabel lblHeaderAction = new JLabel("Quyền hạn");
        lblHeaderAction.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblHeaderAction.setForeground(textGray);
        lblHeaderAction.setBorder(new EmptyBorder(0, 10, 0, 0));
        tablePanel.add(lblHeaderAction, gbc);

        double roleWeight = 0.8 / roles.length;
        for (int i = 0; i < roles.length; i++) {
            gbc.gridx = i + 1;
            gbc.weightx = roleWeight;
            JLabel lblRole = new JLabel(roles[i], SwingConstants.CENTER);
            lblRole.setFont(new Font("Segoe UI", Font.BOLD, 15));
            lblRole.setForeground(textDark);
            tablePanel.add(lblRole, gbc);
        }

        // --- CÁC DÒNG DỮ LIỆU ---
        for (int i = 0; i < actions.length; i++) {
            gbc.gridy = i + 1;
            // --- CHÌA KHÓA Ở ĐÂY: Ép các hàng giãn đều ra lấp đầy khoảng trắng bên dưới ---
            gbc.weighty = 1.0; 
            gbc.insets = new Insets(0, 0, 0, 0); 
            
            boolean isAddAction = actions[i].equals("+ Thêm quyền hạn");

            // Cột 1: Tên quyền (Xem, Thêm... hoặc + Thêm quyền hạn)
            gbc.gridx = 0;
            JPanel cellAction = new JPanel(new BorderLayout());
            cellAction.setBackground(cardWhite);
            cellAction.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, borderGray));
            
            JLabel lblAction = new JLabel(actions[i]);
            lblAction.setFont(new Font("Segoe UI", Font.BOLD, 14));
            
            // Xử lý riêng giao diện cho dòng "Thêm quyền hạn"
            if (isAddAction) {
                lblAction.setForeground(primaryBlue); // Đổi màu xanh cho nổi bật
                lblAction.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Đổi con trỏ chuột thành hình bàn tay
            } else {
                lblAction.setForeground(textDark);
            }
            
            lblAction.setBorder(new EmptyBorder(20, 10, 20, 0)); 
            cellAction.add(lblAction, BorderLayout.CENTER);
            tablePanel.add(cellAction, gbc);

            // Các cột Checkbox
            for (int j = 0; j < roles.length; j++) {
                gbc.gridx = j + 1;
                
                JPanel cellCb = new JPanel(new GridBagLayout());
                cellCb.setBackground(cardWhite);
                cellCb.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, borderGray));
                
                // NẾU KHÔNG PHẢI LÀ DÒNG "THÊM QUYỀN HẠN" THÌ MỚI VẼ CHECKBOX
                if (!isAddAction) {
                    JCheckBox cb = new JCheckBox();
                    cb.setBackground(cardWhite);
                    cb.setCursor(new Cursor(Cursor.HAND_CURSOR));
                    
                    // Logic tick ảo
                    if (j == 0) {
                        cb.setSelected(true);
                    } else if (j == 1 && i <= 2) {
                        cb.setSelected(true);
                    } else if ((j == 2 || j == 3) && i == 0) {
                        cb.setSelected(true);
                    }
                    cellCb.add(cb);
                }
                
                tablePanel.add(cellCb, gbc);
            }
        }

        JScrollPane scroll = new JScrollPane(tablePanel);
        scroll.setBorder(null);
        scroll.getViewport().setBackground(cardWhite);
        container.add(scroll, BorderLayout.CENTER);

        JPanel bottomBtns = new JPanel(new FlowLayout(FlowLayout.RIGHT, 0, 0));
        bottomBtns.setBackground(cardWhite);
        bottomBtns.setBorder(new EmptyBorder(20, 0, 0, 0));
        JButton btnSave = createCustomButton("Lưu thay đổi", primaryBlue, Color.WHITE);
        bottomBtns.add(btnSave);
        container.add(bottomBtns, BorderLayout.SOUTH);

        return container;
    }
    // =========================================================
    // UI COMPONENTS TIỆN ÍCH
    // =========================================================
    
    private JButton createCustomButton(String text, Color bg, Color fg) {
        JButton btn = new JButton(text) {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(bg);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 10, 10);
                super.paintComponent(g);
                g2.dispose();
            }
        };
        btn.setFont(new Font("Segoe UI", Font.BOLD, 13));
        btn.setForeground(fg);
        btn.setPreferredSize(new Dimension(160, 40));
        btn.setContentAreaFilled(false);
        btn.setBorderPainted(false);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        return btn;
    }

    class RoundedPanel extends JPanel {
        private int radius;
        private Color bgColor;

        public RoundedPanel(int radius, Color bgColor) {
            this.radius = radius;
            this.bgColor = bgColor;
            setOpaque(false);
        }

        @Override
        protected void paintComponent(Graphics g) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(bgColor);
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), radius, radius);
            g2.dispose();
            super.paintComponent(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
