/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author nguye
 */
public class RoleManagementPanel extends javax.swing.JPanel {

    private final Color bgLight = new Color(244, 246, 250); // Màu trắng ngả xám hiện đại
    private final Color cardWhite = Color.WHITE;
    private final Color textDark = new Color(43, 54, 116);
    private final Color textGray = new Color(163, 174, 208);
    private final Color primaryBlue = new Color(67, 97, 238);
    private final Color borderGray = new Color(230, 235, 241);

    private List<String> roleList;
    private List<String> actionList;
    private String searchRoleQuery = ""; 
    
    private JPanel matrixContainer;

    public RoleManagementPanel() {
        // Khởi tạo dữ liệu
        roleList = new ArrayList<>(Arrays.asList("Quản trị viên", "Quản lý cửa hàng", "Nhân viên bán hàng", "Nhân viên kho"));
        actionList = new ArrayList<>(Arrays.asList("Xem", "Thêm", "Sửa", "Xóa", "Xuất file", "+ Thêm quyền hạn"));
        
        initComponents();
        setupModernLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
   private void setupModernLayout() {
        this.removeAll();
        this.setLayout(new BorderLayout(0, 20));
        this.setBackground(bgLight);
        this.setBorder(new EmptyBorder(30, 30, 30, 30));

        JPanel header = new JPanel(new BorderLayout());
        header.setBackground(bgLight);
        
        JPanel titlePanel = new JPanel(new GridLayout(2, 1, 0, 5));
        titlePanel.setBackground(bgLight);
        JLabel title = new JLabel("Ma Trận Phân Quyền");
        title.setFont(new Font("Segoe UI", Font.BOLD, 26));
        title.setForeground(textDark);
        JLabel subtitle = new JLabel("Quản lý tập trung quyền hạn của tất cả các vai trò trong hệ thống");
        subtitle.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        subtitle.setForeground(textGray);
        titlePanel.add(title);
        titlePanel.add(subtitle);
        
        JPanel rightHeader = new JPanel(new FlowLayout(FlowLayout.RIGHT, 15, 0));
        rightHeader.setBackground(bgLight);
        
        JTextField txtSearchRole = new JTextField(15);
        txtSearchRole.putClientProperty("JTextField.placeholderText", "Tìm vai trò...");
        txtSearchRole.setPreferredSize(new Dimension(200, 40));
        txtSearchRole.setBorder(BorderFactory.createCompoundBorder(
                new RoundBorder(borderGray, 10), new EmptyBorder(5, 15, 5, 15)
        ));
        
        txtSearchRole.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { updateSearch(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { updateSearch(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { updateSearch(); }
            private void updateSearch() {
                searchRoleQuery = txtSearchRole.getText().toLowerCase().trim();
                refreshMatrix(); 
            }
        });
        
        JButton btnAddNew = createCustomButton("+ Thêm vai trò mới", primaryBlue, Color.WHITE);
        btnAddNew.addActionListener(e -> showAddRoleDialog());
        
        rightHeader.add(txtSearchRole);
        rightHeader.add(btnAddNew);
        
        header.add(titlePanel, BorderLayout.WEST);
        header.add(rightHeader, BorderLayout.EAST);
        this.add(header, BorderLayout.NORTH);

        matrixContainer = new JPanel(new BorderLayout());
        matrixContainer.setBackground(bgLight);
        
        refreshMatrix();
        this.add(matrixContainer, BorderLayout.CENTER);
    }

    private void refreshMatrix() {
        matrixContainer.removeAll();
        matrixContainer.add(createMatrixPanel(), BorderLayout.CENTER);
        matrixContainer.revalidate();
        matrixContainer.repaint();
    }

    private java.awt.image.BufferedImage blurImage(java.awt.image.BufferedImage img) {
        int radius = 10; 
        float[] matrix = new float[radius * radius];
        for (int i = 0; i < matrix.length; i++) matrix[i] = 1.0f / matrix.length;
        
        java.awt.image.ConvolveOp op = new java.awt.image.ConvolveOp(new java.awt.image.Kernel(radius, radius, matrix), java.awt.image.ConvolveOp.EDGE_NO_OP, null);
        java.awt.image.BufferedImage blurred = new java.awt.image.BufferedImage(img.getWidth(), img.getHeight(), java.awt.image.BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = blurred.createGraphics(); g2.drawImage(img, 0, 0, null); g2.dispose();
        return op.filter(blurred, null);
    }

    private JPanel createBlurBackgroundPanel(Window parentWindow, java.awt.image.BufferedImage blurredBg) {
        JPanel blurBgPanel = new JPanel(new GridBagLayout()) {
            @Override protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create(); g2.drawImage(blurredBg, 0, 0, null);
                g2.setColor(new Color(0, 0, 0, 40)); g2.fillRect(0, 0, getWidth(), getHeight()); g2.dispose(); super.paintComponent(g);
            }
        };
        blurBgPanel.setOpaque(false); blurBgPanel.setPreferredSize(new Dimension(parentWindow.getWidth(), parentWindow.getHeight())); return blurBgPanel;
    }

    private String showCustomInputDialog(String title, String subtitle, String placeholder) {
        Window parentWindow = SwingUtilities.getWindowAncestor(this);
        java.awt.image.BufferedImage capture = new java.awt.image.BufferedImage(parentWindow.getWidth(), parentWindow.getHeight(), java.awt.image.BufferedImage.TYPE_INT_ARGB);
        parentWindow.paint(capture.getGraphics());
        java.awt.image.BufferedImage blurredBg = blurImage(capture);
        
        JDialog dialog = new JDialog(parentWindow, Dialog.ModalityType.APPLICATION_MODAL);
        dialog.setUndecorated(true); dialog.setBackground(new Color(0, 0, 0, 0)); 

        JPanel blurBgPanel = createBlurBackgroundPanel(parentWindow, blurredBg);
        RoundedPanel contentPanel = new RoundedPanel(20, cardWhite); contentPanel.setLayout(new BorderLayout(0, 20));
        contentPanel.setBorder(BorderFactory.createCompoundBorder(new RoundBorder(new Color(200, 205, 220), 20), new EmptyBorder(25, 30, 25, 30))); contentPanel.setOpaque(false);

        JPanel header = new JPanel(new GridLayout(2, 1, 0, 5)); header.setOpaque(false);
        JLabel lblTitle = new JLabel(title); lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 22)); lblTitle.setForeground(textDark);
        JLabel lblSub = new JLabel(subtitle); lblSub.setFont(new Font("Segoe UI", Font.PLAIN, 13)); lblSub.setForeground(textGray);
        header.add(lblTitle); header.add(lblSub); contentPanel.add(header, BorderLayout.NORTH);

        JTextField txtInput = new JTextField(); txtInput.setFont(new Font("Segoe UI", Font.PLAIN, 15)); txtInput.setPreferredSize(new Dimension(320, 45));
        txtInput.setBorder(BorderFactory.createCompoundBorder(new RoundBorder(borderGray, 10), new EmptyBorder(5, 15, 5, 15)));
        txtInput.putClientProperty("JTextField.placeholderText", placeholder);
        
        if (!placeholder.startsWith("Ví dụ:")) txtInput.setText(placeholder);
        contentPanel.add(txtInput, BorderLayout.CENTER);

        JPanel footer = new JPanel(new FlowLayout(FlowLayout.RIGHT, 10, 0)); footer.setOpaque(false); final String[] result = {null};
        JButton btnCancel = createCustomButton("Hủy", new Color(235, 238, 244), textDark); btnCancel.setPreferredSize(new Dimension(100, 40));
        btnCancel.addActionListener(e -> dialog.dispose()); 
        JButton btnOk = createCustomButton("Xác nhận", primaryBlue, Color.WHITE); btnOk.setPreferredSize(new Dimension(120, 40));
        btnOk.addActionListener(e -> { result[0] = txtInput.getText(); dialog.dispose(); });
        footer.add(btnCancel); footer.add(btnOk); contentPanel.add(footer, BorderLayout.SOUTH);

        GridBagConstraints gbc = new GridBagConstraints(); gbc.gridx = 0; gbc.gridy = 0; blurBgPanel.add(contentPanel, gbc);
        dialog.add(blurBgPanel); dialog.pack(); dialog.setLocationRelativeTo(parentWindow); dialog.setVisible(true);
        return result[0];
    }

    private String showRoleActionDialog(String roleName) {
        Window parentWindow = SwingUtilities.getWindowAncestor(this);
        java.awt.image.BufferedImage capture = new java.awt.image.BufferedImage(parentWindow.getWidth(), parentWindow.getHeight(), java.awt.image.BufferedImage.TYPE_INT_ARGB);
        parentWindow.paint(capture.getGraphics());
        java.awt.image.BufferedImage blurredBg = blurImage(capture);
        
        JDialog dialog = new JDialog(parentWindow, Dialog.ModalityType.APPLICATION_MODAL);
        dialog.setUndecorated(true); dialog.setBackground(new Color(0, 0, 0, 0)); 

        JPanel blurBgPanel = createBlurBackgroundPanel(parentWindow, blurredBg);
        RoundedPanel contentPanel = new RoundedPanel(20, cardWhite); contentPanel.setLayout(new BorderLayout(0, 20));
        contentPanel.setBorder(BorderFactory.createCompoundBorder(new RoundBorder(new Color(200, 205, 220), 20), new EmptyBorder(25, 30, 25, 30))); contentPanel.setOpaque(false);

        JPanel header = new JPanel(new GridLayout(2, 1, 0, 5)); header.setOpaque(false);
        JLabel lblTitle = new JLabel("Tùy Chọn Vai Trò"); lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 22)); lblTitle.setForeground(textDark);
        JLabel lblSub = new JLabel("Bạn muốn thao tác gì với vai trò '" + roleName + "'?"); lblSub.setFont(new Font("Segoe UI", Font.PLAIN, 13)); lblSub.setForeground(textGray);
        header.add(lblTitle); header.add(lblSub); contentPanel.add(header, BorderLayout.NORTH);

        JPanel actionPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 15, 10)); actionPanel.setOpaque(false); final String[] result = {null};
        JButton btnRename = createCustomButton("Đổi tên", primaryBlue, Color.WHITE); btnRename.addActionListener(e -> { result[0] = "RENAME"; dialog.dispose(); });
        JButton btnDelete = createCustomButton("Xóa vai trò", new Color(220, 53, 69), Color.WHITE); btnDelete.addActionListener(e -> { result[0] = "DELETE"; dialog.dispose(); });
        actionPanel.add(btnRename); actionPanel.add(btnDelete); contentPanel.add(actionPanel, BorderLayout.CENTER);

        JPanel footer = new JPanel(new FlowLayout(FlowLayout.RIGHT, 0, 0)); footer.setOpaque(false);
        JButton btnCancel = createCustomButton("Hủy bỏ", new Color(235, 238, 244), textDark); btnCancel.setPreferredSize(new Dimension(100, 40));
        btnCancel.addActionListener(e -> dialog.dispose()); footer.add(btnCancel); contentPanel.add(footer, BorderLayout.SOUTH);

        GridBagConstraints gbc = new GridBagConstraints(); gbc.gridx = 0; gbc.gridy = 0; blurBgPanel.add(contentPanel, gbc);
        dialog.add(blurBgPanel); dialog.pack(); dialog.setLocationRelativeTo(parentWindow); dialog.setVisible(true);
        return result[0];
    }

    private String showPasswordConfirmDialog() {
        Window parentWindow = SwingUtilities.getWindowAncestor(this);
        java.awt.image.BufferedImage capture = new java.awt.image.BufferedImage(parentWindow.getWidth(), parentWindow.getHeight(), java.awt.image.BufferedImage.TYPE_INT_ARGB);
        parentWindow.paint(capture.getGraphics());
        java.awt.image.BufferedImage blurredBg = blurImage(capture);
        
        JDialog dialog = new JDialog(parentWindow, Dialog.ModalityType.APPLICATION_MODAL);
        dialog.setUndecorated(true); dialog.setBackground(new Color(0, 0, 0, 0)); 

        JPanel blurBgPanel = createBlurBackgroundPanel(parentWindow, blurredBg);
        RoundedPanel contentPanel = new RoundedPanel(20, cardWhite); contentPanel.setLayout(new BorderLayout(0, 20));
        contentPanel.setBorder(BorderFactory.createCompoundBorder(new RoundBorder(new Color(200, 205, 220), 20), new EmptyBorder(25, 30, 25, 30))); contentPanel.setOpaque(false);

        JPanel header = new JPanel(new GridLayout(2, 1, 0, 5)); header.setOpaque(false);
        JLabel lblTitle = new JLabel("Xác Thực Bảo Mật"); lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 22)); lblTitle.setForeground(new Color(220, 53, 69)); 
        JLabel lblSub = new JLabel("Vui lòng nhập mật khẩu Quản trị viên để tiến hành xóa:"); lblSub.setFont(new Font("Segoe UI", Font.PLAIN, 13)); lblSub.setForeground(textGray);
        header.add(lblTitle); header.add(lblSub); contentPanel.add(header, BorderLayout.NORTH);

        JPasswordField txtPass = new JPasswordField(); txtPass.setFont(new Font("Segoe UI", Font.PLAIN, 15)); txtPass.setPreferredSize(new Dimension(320, 45));
        txtPass.setBorder(BorderFactory.createCompoundBorder(new RoundBorder(borderGray, 10), new EmptyBorder(5, 15, 5, 15))); contentPanel.add(txtPass, BorderLayout.CENTER);

        JPanel footer = new JPanel(new FlowLayout(FlowLayout.RIGHT, 10, 0)); footer.setOpaque(false); final String[] result = {null};
        JButton btnCancel = createCustomButton("Hủy", new Color(235, 238, 244), textDark); btnCancel.setPreferredSize(new Dimension(100, 40)); btnCancel.addActionListener(e -> dialog.dispose()); 
        JButton btnOk = createCustomButton("Xác nhận", new Color(220, 53, 69), Color.WHITE); btnOk.setPreferredSize(new Dimension(120, 40));
        btnOk.addActionListener(e -> { result[0] = new String(txtPass.getPassword()); dialog.dispose(); });
        footer.add(btnCancel); footer.add(btnOk); contentPanel.add(footer, BorderLayout.SOUTH);

        GridBagConstraints gbc = new GridBagConstraints(); gbc.gridx = 0; gbc.gridy = 0; blurBgPanel.add(contentPanel, gbc);
        dialog.add(blurBgPanel); dialog.pack(); dialog.setLocationRelativeTo(parentWindow); dialog.setVisible(true);
        return result[0];
    }

    private void showAddRoleDialog() {
        String newRole = showCustomInputDialog("Thêm Vai Trò Mới", "Nhập tên chức danh/vai trò muốn tạo:", "Ví dụ: Thực tập sinh...");
        if (newRole != null && !newRole.trim().isEmpty()) { roleList.add(newRole.trim()); refreshMatrix(); }
    }

    private void showAddActionDialog() {
        String newAction = showCustomInputDialog("Thêm Quyền Hạn", "Nhập tên thao tác hoặc phân hệ mới:", "Ví dụ: Phê duyệt đơn...");
        if (newAction != null && !newAction.trim().isEmpty()) { actionList.add(actionList.size() - 1, newAction.trim()); refreshMatrix(); }
    }

    private void handleRoleClick(String roleName) {
        int realIndex = roleList.indexOf(roleName); 
        if (realIndex == -1) return; 
        
        String action = showRoleActionDialog(roleName);
        if ("DELETE".equals(action)) {
            String pass = showPasswordConfirmDialog();
            if (pass != null) {
                if ("admin".equals(pass)) { roleList.remove(realIndex); refreshMatrix(); JOptionPane.showMessageDialog(this, "Vai trò được xóa thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE); }
                else { JOptionPane.showMessageDialog(this, "Không thể xóa vai trò. Sai mật khẩu!", "Lỗi", JOptionPane.ERROR_MESSAGE); }
            }
        } else if ("RENAME".equals(action)) {
            String newName = showCustomInputDialog("Đổi Tên Vai Trò", "Nhập tên mới để thay thế cho '" + roleName + "':", roleName);
            if (newName != null && !newName.trim().isEmpty()) {
                if (!newName.trim().equals(roleName)) { roleList.set(realIndex, newName.trim()); refreshMatrix(); JOptionPane.showMessageDialog(this, "Đổi tên vai trò thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE); }
            }
        }
    }

    // =========================================================
    // PHẦN BẢNG MA TRẬN (ĐÃ LẬT TRỤC X-Y VÀ THU GỌN PADDING)
    // =========================================================
    private JPanel createMatrixPanel() {
        RoundedPanel container = new RoundedPanel(20, cardWhite);
        container.setLayout(new BorderLayout(0, 20));
        container.setBorder(new EmptyBorder(25, 25, 25, 25)); // Thu hẹp lề một chút

        JPanel tablePanel = new JPanel(new GridBagLayout());
        tablePanel.setBackground(cardWhite);
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.BOTH;

        // --- 1. DÒNG HEADER: CÁC QUYỀN HẠN LÀM CỘT ---
        gbc.gridy = 0; 
        gbc.weighty = 0.0; 
        gbc.insets = new Insets(0, 0, 15, 0); // Thu hẹp khoảng cách dưới header
        
        // Ô góc trái trên: Chữ "Vai trò"
        gbc.gridx = 0; 
        gbc.weightx = 0.25; // Cho cột tên Role chiếm 25% chiều rộng
        JLabel lblHeaderRole = new JLabel("Vai trò"); 
        lblHeaderRole.setFont(new Font("Segoe UI", Font.BOLD, 15)); 
        lblHeaderRole.setForeground(textGray); 
        lblHeaderRole.setBorder(new EmptyBorder(0, 10, 0, 0));
        tablePanel.add(lblHeaderRole, gbc);

        // Các cột Quyền (Xem, Thêm, Sửa...)
        double actionWeight = 0.75 / actionList.size(); 
        for (int i = 0; i < actionList.size(); i++) {
            gbc.gridx = i + 1;
            gbc.weightx = actionWeight;
            
            String currentAction = actionList.get(i);
            boolean isAddAction = currentAction.equals("+ Thêm quyền hạn");
            
            JLabel lblAction = new JLabel(currentAction, SwingConstants.CENTER);
            lblAction.setFont(new Font("Segoe UI", Font.BOLD, 14));
            
            if (isAddAction) {
                lblAction.setForeground(primaryBlue); 
                lblAction.setCursor(new Cursor(Cursor.HAND_CURSOR));
                lblAction.addMouseListener(new MouseAdapter() { @Override public void mouseClicked(MouseEvent e) { showAddActionDialog(); } });
            } else {
                lblAction.setForeground(textDark);
            }
            tablePanel.add(lblAction, gbc);
        }

        // --- 2. CÁC DÒNG DỮ LIỆU: CÁC VAI TRÒ LÀM HÀNG ---
        List<String> displayRoles = new ArrayList<>();
        for (String r : roleList) {
            if (r.toLowerCase().contains(searchRoleQuery)) { displayRoles.add(r); }
        }

        for (int i = 0; i < displayRoles.size(); i++) {
            gbc.gridy = i + 1; 
            gbc.weighty = 0.0; // THU GỌN: Tắt giãn nở chiều dọc để các hàng dính sát vào nhau
            gbc.insets = new Insets(0, 0, 0, 0); 
            
            String currentRole = displayRoles.get(i);

            // Cột 1: Tên Vai Trò
            gbc.gridx = 0;
            JPanel cellRole = new JPanel(new BorderLayout()); 
            cellRole.setBackground(cardWhite); 
            cellRole.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, borderGray));
            
            JLabel lblRole = new JLabel(currentRole); 
            lblRole.setFont(new Font("Segoe UI", Font.BOLD, 14));
            lblRole.setForeground(textDark); 
            lblRole.setCursor(new Cursor(Cursor.HAND_CURSOR));
            lblRole.addMouseListener(new MouseAdapter() { @Override public void mouseClicked(MouseEvent e) { handleRoleClick(currentRole); } });
            
            // THU GỌN PADDING: Chỉ cách trên dưới 12px thay vì 20px như cũ
            lblRole.setBorder(new EmptyBorder(12, 10, 12, 0)); 
            cellRole.add(lblRole, BorderLayout.CENTER);
            tablePanel.add(cellRole, gbc);

            // Cột 2..N: Checkbox Quyền Hạn
            for (int j = 0; j < actionList.size(); j++) {
                gbc.gridx = j + 1;
                JPanel cellCb = new JPanel(new GridBagLayout()); 
                cellCb.setBackground(cardWhite); 
                cellCb.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, borderGray));
                
                String currentAction = actionList.get(j);
                boolean isAddAction = currentAction.equals("+ Thêm quyền hạn");
                
                if (!isAddAction) {
                    JCheckBox cb = new JCheckBox(); 
                    cb.setBackground(cardWhite); 
                    cb.setCursor(new Cursor(Cursor.HAND_CURSOR));
                    
                    // Logic tick ảo tương ứng (i = vai trò, j = quyền hạn)
                    if (currentRole.equals("Quản trị viên")) cb.setSelected(true);
                    else if (currentRole.equals("Quản lý cửa hàng") && j <= 2) cb.setSelected(true); // Chỉ Xem, Thêm, Sửa
                    else if ((currentRole.equals("Nhân viên bán hàng") || currentRole.equals("Nhân viên kho")) && j == 0) cb.setSelected(true); // Chỉ Xem
                    
                    cellCb.add(cb);
                }
                tablePanel.add(cellCb, gbc);
            }
        }
        
        // --- 3. ĐIỂM CHỐT (MAGIC TRICK): Thêm Panel đẩy để nén khoảng trống ---
        gbc.gridy = displayRoles.size() + 1;
        gbc.weighty = 1.0; // Panel vô hình này sẽ hút hết khoảng trống thừa bên dưới
        gbc.gridx = 0;
        gbc.gridwidth = actionList.size() + 1; // Kéo dài qua tất cả các cột
        JPanel filler = new JPanel();
        filler.setBackground(cardWhite);
        tablePanel.add(filler, gbc);

        JScrollPane scroll = new JScrollPane(tablePanel);
        scroll.setBorder(null); scroll.getViewport().setBackground(cardWhite);
        container.add(scroll, BorderLayout.CENTER);

        JPanel bottomBtns = new JPanel(new FlowLayout(FlowLayout.RIGHT, 0, 0)); 
        bottomBtns.setBackground(cardWhite); 
        bottomBtns.setBorder(new EmptyBorder(15, 0, 0, 0));
        JButton btnSave = createCustomButton("Lưu thay đổi", primaryBlue, Color.WHITE); bottomBtns.add(btnSave);
        container.add(bottomBtns, BorderLayout.SOUTH);

        return container;
    }

    private JButton createCustomButton(String text, Color bg, Color fg) {
        JButton btn = new JButton(text) {
            @Override protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create(); g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(bg); g2.fillRoundRect(0, 0, getWidth(), getHeight(), 10, 10);
                super.paintComponent(g); g2.dispose();
            }
        };
        btn.setFont(new Font("Segoe UI", Font.BOLD, 13)); btn.setForeground(fg); btn.setPreferredSize(new Dimension(160, 40));
        btn.setContentAreaFilled(false); btn.setBorderPainted(false); btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        return btn;
    }

    class RoundedPanel extends JPanel {
        private int radius; private Color bgColor;
        public RoundedPanel(int radius, Color bgColor) { this.radius = radius; this.bgColor = bgColor; setOpaque(false); }
        @Override protected void paintComponent(Graphics g) {
            Graphics2D g2 = (Graphics2D) g.create(); g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(bgColor); g2.fillRoundRect(0, 0, getWidth(), getHeight(), radius, radius); g2.dispose(); super.paintComponent(g);
        }
    }

    class RoundBorder implements javax.swing.border.Border {
        private Color color; private int radius;
        public RoundBorder(Color color, int radius) { this.color = color; this.radius = radius; }
        @Override public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            Graphics2D g2 = (Graphics2D) g.create(); g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(color); g2.setStroke(new BasicStroke(1.2f)); g2.drawRoundRect(x, y, width - 1, height - 1, radius, radius); g2.dispose();
        }
        @Override public Insets getBorderInsets(Component c) { return new Insets(1, 1, 1, 1); }
        @Override public boolean isBorderOpaque() { return false; }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
