/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.util.List;

/**
 *
 * @author Admin
 */
public class StatisticView extends javax.swing.JPanel {

    /**
     * Creates new form StatisticView
     */
    public StatisticView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTop = new javax.swing.JPanel();
        pnTotalRevenue = new javax.swing.JPanel();
        TotalRevenue = new javax.swing.JLabel();
        pnTotalCustomers = new javax.swing.JPanel();
        TotalCustomers = new javax.swing.JLabel();
        pnTotalOder = new javax.swing.JPanel();
        TotalOrder = new javax.swing.JLabel();
        tbStatistic = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        pnTop.setPreferredSize(new java.awt.Dimension(0, 40));
        pnTop.setLayout(new java.awt.GridLayout(1, 0));

        pnTotalRevenue.setBackground(new java.awt.Color(46, 204, 113));
        pnTotalRevenue.setPreferredSize(new java.awt.Dimension(150, 40));
        pnTotalRevenue.setLayout(new java.awt.GridLayout(1, 0));

        TotalRevenue.setBackground(new java.awt.Color(46, 204, 113));
        TotalRevenue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TotalRevenue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalRevenue.setText("Tổng doanh thu");
        pnTotalRevenue.add(TotalRevenue);

        pnTop.add(pnTotalRevenue);

        pnTotalCustomers.setBackground(new java.awt.Color(243, 156, 18));
        pnTotalCustomers.setPreferredSize(new java.awt.Dimension(150, 40));
        pnTotalCustomers.setLayout(new java.awt.GridLayout(1, 0));

        TotalCustomers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TotalCustomers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalCustomers.setText("Tổng khách hàng");
        pnTotalCustomers.add(TotalCustomers);

        pnTop.add(pnTotalCustomers);

        pnTotalOder.setBackground(new java.awt.Color(52, 152, 219));
        pnTotalOder.setPreferredSize(new java.awt.Dimension(150, 40));
        pnTotalOder.setLayout(new java.awt.GridLayout(1, 0));

        TotalOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TotalOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalOrder.setText("Tổng đơn hàng");
        pnTotalOder.add(TotalOrder);

        pnTop.add(pnTotalOder);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng bán", "Doanh thu"
            }
        ));
        tbStatistic.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTop, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(tbStatistic, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbStatistic, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TotalCustomers;
    private javax.swing.JLabel TotalOrder;
    private javax.swing.JLabel TotalRevenue;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnTop;
    private javax.swing.JPanel pnTotalCustomers;
    private javax.swing.JPanel pnTotalOder;
    private javax.swing.JPanel pnTotalRevenue;
    private javax.swing.JScrollPane tbStatistic;
    // End of variables declaration//GEN-END:variables
}
