/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;
import java.awt.*;
import view.components.WarehouseSidebar;

/**
 *
 * @author nguye
 */
public class WarehouseDashboardView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WarehouseDashboardView.class.getName());
    
    private JPanel mainContentPanel;
    private WarehouseSidebar warehouseSidebar;
    private Color bgWarehouse = new Color(244, 246, 250); // Nền xám sáng hiện đại
    
    public WarehouseDashboardView() {
        initComponents();
        setupWarehouseUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupWarehouseUI() {
        model.account.Account currentUser = business.service.LoginService.getCurrentUser();
        String username = (currentUser != null) ? currentUser.getUsername() : "Nhân viên Kho";

        this.setTitle("SMART SUPERMARKET - WAREHOUSE PORTAL | " + username);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); // <--- THÊM JFrame. VÀO ĐÂY
        this.setMinimumSize(new Dimension(1024, 768));
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // <--- THÊM JFrame. VÀO ĐÂY
        
        // Khởi tạo Sidebar Kho
        warehouseSidebar = new WarehouseSidebar();
        
        // Điều hướng các mục Menu
        warehouseSidebar.setMenuClickListener(title -> {
            switch (title) {
                case "Tổng quan kho":
                    // showPanel(new view.InventoryOverviewPanel());
                    break;
                case "Quản lý tồn kho":
                    // showPanel(new view.InventoryManagementPanel());
                    break;
                case "Quản lý sản phẩm":
                    showPanel(new view.ProductView()); // Gắn thẳng màn hình ProductView vào đây
                    break;
                case "Nhà cung cấp":
                    // showPanel(new view.SupplierView());
                    break;
                case "Danh mục & Thuế VAT":
                    // showPanel(new view.CategoryTaxView());
                    break;
                case "Cài đặt":
                    // showPanel(new view.SettingsView());
                    break;
                case "Đăng xuất":
                    handleLogout();
                    break;
            }
        });

        // Thiết lập Layout chính
        this.getContentPane().setLayout(new BorderLayout());
        this.getContentPane().add(warehouseSidebar, BorderLayout.WEST);
        
        mainContentPanel = new JPanel(new BorderLayout());
        mainContentPanel.setBackground(bgWarehouse);
        this.getContentPane().add(mainContentPanel, BorderLayout.CENTER);
    }

    public void showPanel(JPanel panel) {
        mainContentPanel.removeAll();
        mainContentPanel.add(panel, BorderLayout.CENTER);
        mainContentPanel.revalidate();
        mainContentPanel.repaint();
    }

    private void handleLogout() {
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất khỏi Cổng Kho Hàng?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            business.service.LoginService.logout();
            new LoginView().setVisible(true);
            this.dispose();
        }
    }

    public static void main(String args[]) {
        try {
            com.formdev.flatlaf.FlatLightLaf.setup();
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new WarehouseDashboardView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
